version: '3.7'

networks:
  app-net:

services:
  app:
    build:
      context: .
      dockerfile: .docker/dockerfile
    image: fastapi-template_app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - app-net
  
  db:
    image: postgres:11.6
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - app-net
    ports:
      - "5432:5432"
  
  migration:
    env_file:
      - .env
    image: fastapi-template_app
    volumes:
      - .:/app
    profiles:
      - tools
    depends_on:
      - db
    networks:
      - app-net
